#define BUTTON_TRIGGER_Pin 0
#define BUTTON_TRIGGER_GPIO_Port 0
#define ADC_HALL_Pin 0
#define ADC_HALL_GPIO_Port 0
#define ADC_BAT_Pin 0
#define ADC_BAT_GPIO_Port 0
#define CHARGER_STANDBY_Pin 0
#define CHARGER_STANDBY_GPIO_Port 0
#define CHARGER_CHARGE_Pin 0
#define CHARGER_CHARGE_GPIO_Port 0
#define CHARGER_ENABLE_Pin 0
#define CHARGER_ENABLE_GPIO_Port 0
#define NRF24_IRQ_EXTI_Pin 0
#define NRF24_IRQ_EXTI_GPIO_Port 0
#define NRF24_CE_Pin 0
#define NRF24_CE_GPIO_Port 0
#define NRF24_CSN_Pin 0
#define NRF24_CSN_GPIO_Port 0
#define DCDC_ENABLE_Pin 0
#define DCDC_ENABLE_GPIO_Port 0
#define LED_USER_Pin 0
#define LED_USER_GPIO_Port 0